<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') exit(1);
putenv('APP_ENV=local'); putenv('LUMS_DB_DSN=sqlite::memory:');
putenv('LUMS_SESSION_PATH='.sys_get_temp_dir().'/lums-lifecycle-'.bin2hex(random_bytes(8)));
require dirname(__DIR__).'/src/bootstrap.php';
initialize_database(db(),true); start_lums_session();
$admin=(int)db()->query("SELECT id FROM users WHERE role='admin'")->fetchColumn();
$lecturer=(int)db()->query("SELECT id FROM users WHERE role='lecturer'")->fetchColumn();
$_SESSION['user_id']=$admin; $_SESSION['last_activity']=time();
$checks=0;
$expect=static function(bool $ok,string $message)use(&$checks):void{if(!$ok)throw new RuntimeException($message);$checks++;echo "PASS: $message\n";};
$rooms=array_values(array_filter(list_rooms(),fn($r)=>$r['status']==='available')); $room=$rooms[0]['id']; $otherRoom=$rooms[1]['id'];
$input=['room_id'=>$room,'lecturer_user_id'=>$admin,'course_code'=>'LIFE101','course_name'=>'ทดสอบวงจรคลาสสมมติ','starts_at'=>'2030-05-06T09:00','ends_at'=>'2030-05-06T13:00'];
$made=create_class_session($input); $expect($made['ok'],'Create four continuous hours');
$id=$made['id']; $session=get_class_session($id); $token=$session['qr_token'];
$expect(strtotime($session['ends_at'])-strtotime($session['starts_at'])===14400,'Four-hour duration stored exactly');
$expect(!create_class_session(array_replace($input,['room_id'=>$otherRoom]))['ok'],'All creation paths reject lecturer conflicts');
$expect(!create_class_session(array_replace($input,['starts_at'=>'2030-05-06T08:00','ends_at'=>'2030-05-06T14:00']))['ok'],'Spanning an occupied period is rejected');
$state=['status'=>'open','starts_at'=>'2030-01-01T01:00:00Z','ends_at'=>'2030-01-01T05:00:00Z','checkin_mode'=>'scheduled'];
$expect(class_checkin_status($state,strtotime($state['starts_at'])-1)==='scheduled','Before start waits');
$expect(class_checkin_status($state,strtotime($state['starts_at']))==='open','Exact start accepts');
$expect(class_checkin_status($state,strtotime($state['ends_at'])-1)==='open','Before end accepts');
$expect(class_checkin_status($state,strtotime($state['ends_at']))==='overdue','Exact end stops scheduled admission');
$pastStart=gmdate('Y-m-d\TH:i:s\Z',time()-14400); $pastEnd=gmdate('Y-m-d\TH:i:s\Z',time()-7200);
db()->prepare("UPDATE class_sessions SET starts_at=?,ends_at=?,status='draft' WHERE id=?")->execute([$pastStart,$pastEnd,$id]);
$before=get_class_session($id);
$expect(!open_class_session($id,'scheduled')['ok'],'Opening expired automatic admission cannot falsely succeed');
$expect(get_class_session($id)['status']==='draft','Rejected opening leaves state intact');
$expect(open_class_session($id,'manual')['ok'],'Lecturer can explicitly open after the lesson');
$manual=get_class_session($id);
$expect($manual['display_status']==='open' && $manual['checkin_mode']==='manual','Manual admission remains open past lesson end');
$expect($manual['starts_at']===$before['starts_at'] && $manual['ends_at']===$before['ends_at'] && $manual['qr_token']===$token,'Opening admission preserves lesson times and QR');
$expect(count(list_class_sessions(['q'=>'LIFE101','status'=>'open']))===1 && list_class_sessions(['q'=>'LIFE101','status'=>'overdue'])===[],'Filters agree with manual status');
$expect(dashboard_data()['active_total']===1 && dashboard_data()['rooms_in_use']===0 && dashboard_data()['issues_total']===0,'Open attendance does not reserve a room outside lesson hours');
$date=(new DateTimeImmutable($pastStart))->setTimezone(new DateTimeZone('Asia/Bangkok'))->format('Y-m-d');
$report=usage_report(planning_filters(['date_from'=>$date,'date_to'=>$date,'q'=>'LIFE101','source'=>'classes'],true));
$expect($report['events']===1 && str_contains(usage_source_label($report['rows'][0]),'คลาสเปิดลงชื่อ'),'Calendar/report label agrees with admission policy');
$student=['student_code'=>'99990001','student_name'=>'นิสิตสมมติ ทดสอบระบบ','client_request_id'=>'lifecycle-request-0001'];
db()->prepare('UPDATE rooms SET capacity=1 WHERE id=?')->execute([$room]);
$saved=register_student_attendance($token,$student);
$expect($saved['ok'],'Student can sign in after explicit manual opening');
$expect((int)db()->query('SELECT id FROM attendance_records')->fetchColumn()===$saved['id'],'Receipt references attendance ID, not audit-log ID');
$savedAt=db()->query('SELECT check_in_at FROM attendance_records')->fetchColumn();
$expect(abs(time()-strtotime($savedAt))<5,'Late sign-in records actual time, not lesson date');
$expect(!register_student_attendance($token,array_replace($student,['student_code'=>'99990002','client_request_id'=>'lifecycle-request-0002']))['ok'],'Full capacity rejects a new student');
$expect(!empty(register_student_attendance($token,$student)['duplicate']),'Duplicate retry succeeds even at full capacity');
$expect(close_class_session($id)['ok'],'Manual close succeeds');
$expect(!register_student_attendance($token,array_replace($student,['student_code'=>'99990002']))['ok'],'Closed class blocks new students');
$expect(open_class_session($id,'manual')['ok'],'Authorized lecturer can reopen a closed class');
$expect(!open_class_session($id,'invalid')['ok'],'Unknown admission modes rejected');
$_SESSION['user_id']=$lecturer;
$expect(!open_class_session($id,'manual')['ok'] && !close_class_session($id)['ok'],'Another lecturer cannot change admission');
$_SESSION['user_id']=$admin;
db()->prepare("UPDATE class_sessions SET status='cancelled' WHERE id=?")->execute([$id]);
$expect(!open_class_session($id,'manual')['ok'] && !close_class_session($id)['ok'],'Cancelled classes cannot be opened or falsely closed');
$expect(create_class_session(array_replace($input,['course_code'=>'LIFE102','checkin_mode'=>'manual']))['ok'],'Explicit manual mode works on creation');
$second=get_class_session((int)db()->query("SELECT id FROM class_sessions WHERE course_code='LIFE102'")->fetchColumn());
$collision=register_student_attendance($second['qr_token'],array_replace($student,['student_code'=>'99990003']));
$expect(!$collision['ok'] && (int)db()->query('SELECT COUNT(*) FROM attendance_records')->fetchColumn()===1,'Request ID reused for another class cannot claim false success');
$expect(register_student_attendance($second['qr_token'],array_replace($student,['student_code'=>'99990003','client_request_id'=>'lifecycle-request-0003']))['ok'],'New request ID can sign into second class');
require __DIR__.'/fixtures/academic-term.php';
$term=fixture_academic_term('2030-06-01','2030-06-30');
$otherTerm=fixture_academic_term('2030-06-01','2030-06-30','2');
$schedule=['term_id'=>$term['id'],'room_id'=>$room,'lecturer_user_id'=>$admin,'course_code'=>'PLAN101','course_name'=>'แผนทดสอบ','day_of_week'=>1,'starts_time'=>'09:00','ends_time'=>'12:00','active_from'=>'2030-06-01','active_until'=>'2030-06-30'];
$planned=create_course_schedule($schedule);$expect($planned['ok'],'Create recurring test schedule');
$expect(!create_course_schedule(array_replace($schedule,['term_id'=>$otherTerm['id']]))['ok'],'Overlapping academic terms still cannot double-book a room');
$expect(!create_class_session(array_replace($input,['starts_at'=>'2030-06-03T10:00','ends_at'=>'2030-06-03T14:00']))['ok'],'Legacy creation cannot bypass recurring conflict checks');
$expect(!create_session_from_schedule($planned['id'],'2030-02-30')['ok'],'Invalid calendar dates rejected for planned QR');
db()->prepare("UPDATE course_schedules SET status='cancelled' WHERE id=?")->execute([$planned['id']]);
$expect(!create_session_from_schedule($planned['id'],'2030-06-03')['ok'],'Cancelled schedule cannot generate new QR');
$expect(!db()->inTransaction(),'Failed/duplicate workflows leave no open transaction');
$legacy = new PDO('sqlite::memory:',null,null,[PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$legacy->exec("CREATE TABLE class_sessions (id INTEGER PRIMARY KEY, starts_at TEXT, ends_at TEXT, qr_token TEXT, status TEXT)");
$legacy->exec("INSERT INTO class_sessions VALUES (1,'2026-08-30T01:00:00Z','2026-08-30T05:00:00Z','unchanged-legacy-token','open')");
ensure_sqlite_academic_columns($legacy); ensure_sqlite_academic_columns($legacy);
$migrated=$legacy->query('SELECT * FROM class_sessions')->fetch();
$expect($migrated['checkin_mode']==='scheduled' && $migrated['status']==='open' && $migrated['qr_token']==='unchanged-legacy-token' && $migrated['ends_at']==='2026-08-30T05:00:00Z','Migration is repeatable and preserves old status, time and QR');
db()->prepare("UPDATE class_sessions SET starts_at=?,ends_at=?,status='closed' WHERE id=?")->execute([gmdate('Y-m-d\TH:i:s\Z',time()-3600),gmdate('Y-m-d\TH:i:s\Z',time()+3600),$second['id']]);
$expect(dashboard_data()['rooms_in_use']===1,'Closing attendance does not free a room during the lesson');
$expect(!create_course_schedule(array_replace($schedule,['active_from'=>'2030-06-31']))['ok'],'Recurring timetable rejects impossible calendar dates');
$shortPlan=create_course_schedule(array_replace($schedule,['active_from'=>'2030-06-03','active_until'=>'2030-06-05']));
$expect($shortPlan['ok'],'Create a short recurring date range');
$expect(create_course_schedule(array_replace($schedule,['term_id'=>$otherTerm['id'],'active_from'=>'2030-06-04','active_until'=>'2030-06-10']))['ok'],'Overlapping date ranges with no shared lesson day do not falsely conflict');
session_write_close(); echo "PASS: $checks class lifecycle checks\n";
