<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') exit(1);
putenv('APP_ENV=local'); putenv('LUMS_DB_DSN=sqlite::memory:');
putenv('LUMS_SESSION_PATH='.sys_get_temp_dir().'/lums-batch-'.bin2hex(random_bytes(8)));
require dirname(__DIR__).'/src/bootstrap.php';
initialize_database(db(),true); start_lums_session();
$admin=(int)db()->query("SELECT id FROM users WHERE role='admin'")->fetchColumn();
$lecturer=(int)db()->query("SELECT id FROM users WHERE role='lecturer'")->fetchColumn();
$_SESSION['user_id']=$admin; $_SESSION['last_activity']=time();
$checks=0;
$expect=static function(bool $ok,string $message) use (&$checks): void { if(!$ok) throw new RuntimeException($message); $checks++; echo "PASS: $message\n"; };
$rooms=list_rooms(); $r1=$rooms[0]['id']; $r2=$rooms[1]['id'];
$slots=[['room_id'=>$r1,'day_of_week'=>6,'starts_time'=>'08:00','ends_time'=>'11:00'],['room_id'=>$r2,'day_of_week'=>7,'starts_time'=>'13:00','ends_time'=>'16:00']];
$input=['class_mode'=>'semester','academic_year'=>2569,'semester'=>'2','lecturer_user_id'=>$lecturer,'course_code'=>'BATCH101','course_name'=>'ปฏิบัติการทดสอบ','slots_json'=>json_encode($slots)];
$before=(int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn();
$beforeTerms=(int)db()->query('SELECT COUNT(*) FROM academic_terms')->fetchColumn();
$preview=class_batch_preview($input);
$expect($preview['ok'] && $preview['count']===36,'Two weekly ranges yield 36 actual lessons across the term');
$expect((int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn()===$before && (int)db()->query('SELECT COUNT(*) FROM academic_terms')->fetchColumn()===$beforeTerms,'Preview creates neither empty terms nor lessons');
$made=create_class_batch($input);
$expect($made['ok'] && count($made['ids'])===36,'Create both rooms and all lessons atomically');
$classes=array_map('get_class_session',$made['ids']);
$expect(count(array_unique(array_column($classes,'qr_token')))===36,'Every lesson has its own unique QR immediately');
$expect(count(array_unique(array_column($classes,'series_key')))===1,'Both weekly ranges are one editable series');
$expect(array_unique(array_column($classes,'status'))===['open'] && array_unique(array_column($classes,'admission_lead_minutes'))===[10],'All lessons are armed for automatic opening ten minutes early');
$session=$classes[0]; $start=strtotime($session['starts_at']); $end=strtotime($session['ends_at']);
$expect(class_checkin_status($session,$start-601)==='scheduled','One second before admission window stays closed');
$expect(class_checkin_status($session,$start-600)==='open','Exact ten-minute boundary opens');
$expect(class_checkin_status($session,$end-1)==='open' && class_checkin_status($session,$end)==='overdue','Exact lesson end stops automatic admission');
close_class_session($session['id']); $closed=get_class_session($session['id']);
$expect(class_checkin_status($closed,$start)==='closed','Owner closure wins over automatic opening');
$events=room_usage_events('2026-11-16','2027-03-21',['q'=>'BATCH101']);
$expect(count($events)===36 && count(array_unique(array_column($events,'key')))===36,'Calendar has one event per lesson, no duplicate reservation layer');
$expect(count(room_usage_events('2027-03-15','2027-03-21',['q'=>'BATCH101']))===2,'Final teaching week is materialized too');
$count=(int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn();
$expect(!create_class_batch($input)['ok'] && (int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn()===$count,'Duplicate room/time batch fails with no partial rows');
$bad=$slots; $bad[1]['day_of_week']=6; $bad[1]['starts_time']='09:00'; $bad[1]['ends_time']='12:00';
$expect(!class_batch_preview(array_replace($input,['academic_year'=>2568,'slots_json'=>json_encode($bad)]))['ok'],'Two rooms cannot double-book the same lecturer within a batch');
foreach (['[]','not json',json_encode([['room_id'=>999]]),json_encode('wrong')] as $json) $expect(!create_class_batch(array_replace($input,['slots_json'=>$json]))['ok'],'Malformed or missing ranges cannot save an empty class');
$expect(!create_class_batch(array_replace($input,['academic_year'=>2999]))['ok'],'No guessed dates for an unsupported academic year');
$expect(!db()->inTransaction(),'Failed validation leaves no transaction open');
$onceSlots=[['room_id'=>$r1,'class_date'=>'2030-07-01','starts_time'=>'09:00','ends_time'=>'12:00'],['room_id'=>$r2,'class_date'=>'2030-07-02','starts_time'=>'13:00','ends_time'=>'16:00'],['room_id'=>$r1,'class_date'=>'2030-07-03','starts_time'=>'09:00','ends_time'=>'12:00']];
$once=create_class_batch(array_replace($input,['class_mode'=>'once','course_code'=>'ONCESET','slots_json'=>json_encode($onceSlots)]));
$expect($once['ok'] && $once['count']===3,'Once mode supports several dated ranges in one save');
$base=get_class_session($once['ids'][0]);
$edit=['class_id'=>$base['id'],'operation'=>'edit','scope'=>'once','room_id'=>$r1,'class_date'=>'2030-07-01','starts_time'=>'10:00','ends_time'=>'13:00','notes'=>'ทดสอบแก้ไข'];
$result=apply_class_change($edit);
$expect($result['ok'] && $result['count']===1,'Edit only one occurrence');
$expect(get_class_session($base['id'])['qr_token']===$base['qr_token'],'Editing preserves the same class QR');
$second=get_class_session($once['ids'][1]);
$editMany=array_replace($edit,['class_id'=>$second['id'],'scope'=>'following','room_id'=>$r2,'class_date'=>'2030-07-02','starts_time'=>'14:00','ends_time'=>'17:00']);
$result=apply_class_change($editMany);
$expect($result['ok'] && $result['count']===2,'Following scope updates selected and subsequent lessons');
$last=get_class_session($once['ids'][2]);
$expect(date('H:i',strtotime($last['starts_at']))==='10:00' && $last['room_id']===$r1,'Relative time shift preserves distinct range times and unchanged rooms');
$expect(date('H:i',strtotime(get_class_session($base['id'])['starts_at']))==='10:00','Earlier occurrence is untouched by following scope');
$expect(!apply_class_change(array_replace($edit,['scope'=>'invalid']))['ok'],'Unknown scope is rejected');
$expect(!apply_class_change(array_replace($edit,['revision'=>'stale']))['ok'],'Stale selected-class revision is rejected');
$_SESSION['user_id']=$lecturer;
$expect(!apply_class_change(array_replace($edit,['class_id'=>(int)db()->query("SELECT id FROM class_sessions WHERE lecturer_user_id=$admin LIMIT 1")->fetchColumn()]))['ok'],'Lecturer cannot modify another owner');
$_SESSION['user_id']=$admin;
db()->prepare('INSERT INTO attendance_records(class_session_id,student_code,student_name,check_in_at,created_at) VALUES (?,?,?,?,?)')->execute([$base['id'],'TEST9001','ผู้ทดสอบสมมติ',utc_now(),utc_now()]);
$beforeProtected=get_class_session($base['id']);
$cancel=apply_class_change(['class_id'=>$base['id'],'scope'=>'all','operation'=>'cancel']);
$expect($cancel['ok'] && $cancel['count']===2 && $cancel['protected']===1,'Whole-series cancellation skips a lesson with attendance');
$expect(get_class_session($base['id'])['status']===$beforeProtected['status'] && count(class_attendance($base['id']))===1,'History and attendance remain intact');
$expect(get_class_session($once['ids'][1])['status']==='cancelled' && get_public_class_by_token($second['qr_token'])['display_status']==='cancelled','Cancelled lesson QR cannot admit students');
$expect(!register_student_attendance($second['qr_token'],['student_code'=>'TEST9002','student_name'=>'ผู้ทดสอบสมมติ'])['ok'],'Cancelled public QR rejects attendance');
$list=operational_class_list(['range'=>'all','series'=>$made['series_key']]);
$expect($list['total']===36 && count($list['rows'])===36,'Class list groups by requested series and reports exact count');
$expect(operational_class_list(['range'=>'today','date'=>'2026-11-21','series'=>$made['series_key']])['total']===1,'Daily class list shows the real day, not all semester rows');
$expect((int)db()->query("SELECT COUNT(*) FROM audit_logs WHERE action LIKE 'class_series_%'")->fetchColumn()>=3,'Scoped mutations leave an audit trail');
initialize_database(db(),false);
$expect(get_class_session($base['id'])['qr_token']===$base['qr_token'] && count(class_attendance($base['id']))===1,'Repeat migration preserves QR and attendance history');

$activeBefore=dashboard_data()['active_total'];
$earlyId=$made['ids'][0];
db()->prepare("UPDATE class_sessions SET status='open',starts_at=?,ends_at=? WHERE id=?")->execute([gmdate('Y-m-d\TH:i:s\Z',time()+300),gmdate('Y-m-d\TH:i:s\Z',time()+3900),$earlyId]);
$expect(class_checkin_status(get_class_session($earlyId))==='open','A lesson five minutes away is actually accepting attendance');
$expect(in_array($earlyId,array_column(operational_class_list(['range'=>'all','status'=>'open'])['rows'],'id'),true),'Operational list agrees with early admission');
$expect(!in_array($earlyId,array_column(operational_class_list(['range'=>'all','status'=>'scheduled'])['rows'],'id'),true),'Early-admission lesson is no longer in waiting filter');
$expect(dashboard_data()['active_total']===$activeBefore+1,'Dashboard accepting count includes the ten-minute admission window');
close_class_session($earlyId);
$expect(dashboard_data()['active_total']===$activeBefore,'Owner closure removes early admission from the dashboard');
$expect(in_array($earlyId,array_column(operational_class_list(['status'=>'closed'])['rows'],'id'),true),'Status-only links search all dates, not just today');
echo "PASS: $checks batch, admission and scoped change checks\n";
