<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') exit(1);
putenv('APP_ENV=local');putenv('LUMS_DB_DSN=sqlite::memory:');
putenv('LUMS_SESSION_PATH='.sys_get_temp_dir().'/lums-once-'.bin2hex(random_bytes(8)));
require dirname(__DIR__).'/src/bootstrap.php';
initialize_database(db(),true);start_lums_session();
$admin=(int)db()->query("SELECT id FROM users WHERE role='admin'")->fetchColumn();
$lecturer=(int)db()->query("SELECT id FROM users WHERE role='lecturer'")->fetchColumn();
$_SESSION['user_id']=$admin;$_SESSION['last_activity']=time();
$checks=0;
$expect=static function(bool $ok,string $message) use (&$checks): void {if(!$ok)throw new RuntimeException($message);$checks++;};
$rooms=list_rooms();$r1=$rooms[0]['id'];$r2=$rooms[1]['id'];
$input=['room_id'=>$r1,'lecturer_user_id'=>$lecturer,'course_code'=>'ONCE101','course_name'=>'คาบทดสอบครั้งเดียว','class_date'=>'2030-05-06','starts_time'=>'09:00','ends_time'=>'10:00'];
$termCount=(int)db()->query('SELECT COUNT(*) FROM academic_terms')->fetchColumn();
$made=create_one_off_session($input);
$expect($made['ok'],'Create a one-off without a matching academic term');
$row=get_class_session($made['id']);
$expect($row['lecturer_user_id']===$lecturer && !$row['schedule_id'],'Admin can assign a lecturer without creating a recurring schedule');
$expect(strlen($row['qr_token'])===32,'One-off gets its own QR token');
$expect((int)db()->query('SELECT COUNT(*) FROM academic_terms')->fetchColumn()===$termCount,'No academic term is implicitly added');
$expect(count(room_usage_events('2030-05-06','2030-05-06'))===1 && !room_usage_events('2030-05-13','2030-05-13'),'Occurrence appears once, not the following week');
$expect(!create_one_off_session($input)['ok'],'Double booking rejected');
$expect(!create_one_off_session(array_replace($input,['room_id'=>$r2]))['ok'],'Lecturer conflict in another room rejected');
$expect(create_one_off_session(array_replace($input,['starts_time'=>'10:00','ends_time'=>'11:00']))['ok'],'Adjacent periods are allowed at exact minute boundaries');
foreach ([['class_date'=>'2030-02-30'],['starts_time'=>'11:00','ends_time'=>'10:00'],['room_id'=>999999],['lecturer_user_id'=>999999],['starts_time'=>'00:00','ends_time'=>'23:59']] as $bad) $expect(!create_one_off_session(array_replace($input,$bad))['ok'],'Invalid booking rejected');
$term=create_academic_term(['academic_year'=>2573,'semester'=>'1','term_starts_on'=>'2030-05-01','term_ends_on'=>'2030-05-31','dates_confirmed'=>'1']);
$schedule=['term_id'=>$term['id'],'room_id'=>$r1,'lecturer_user_id'=>$lecturer,'course_code'=>'WEEK101','course_name'=>'ตารางทดสอบทั้งภาค','day_of_week'=>1,'starts_time'=>'09:00','ends_time'=>'10:00','active_from'=>'2030-05-01','active_until'=>'2030-05-31'];
$expect(!create_course_schedule($schedule)['ok'],'Recurring booking cannot overwrite a one-off');
$scheduled=create_course_schedule(array_replace($schedule,['starts_time'=>'13:00','ends_time'=>'14:00']));
$expect($scheduled['ok'],'Nonconflicting recurring schedule succeeds');
$expect(!create_one_off_session(array_replace($input,['starts_time'=>'13:30','ends_time'=>'14:30']))['ok'],'One-off checks unmaterialized recurring plans');
$busy=one_off_busy_times($r1,$admin,'2030-05-06');
$expect(count($busy)===3 && array_keys($busy[0])===['start','end','reason'],'Availability is anonymous and includes other lecturers');
$generated=create_session_from_schedule($scheduled['id'],'2030-05-06');
db()->prepare("UPDATE class_sessions SET status='cancelled' WHERE id=?")->execute([$generated['id']]);
$expect(create_one_off_session(array_replace($input,['starts_time'=>'13:00','ends_time'=>'14:00']))['ok'],'Cancelled occurrence releases its exact date');
$report=usage_report(planning_filters(['date_from'=>'2030-05-06','date_to'=>'2030-05-06','source'=>'classes','room_id'=>$r1],true));
$expect($report['events']===3 && (float)$report['quantity']===3.0,'One-off reports count duration once');
$_SESSION['user_id']=$lecturer;
$owned=create_one_off_session(array_replace($input,['lecturer_user_id'=>$admin,'class_date'=>'2030-05-07']));
$expect($owned['ok'] && get_class_session($owned['id'])['lecturer_user_id']===$lecturer,'Lecturer cannot spoof ownership');
$expect(local_datetime_to_utc('2030-05-07T09:00')==='2030-05-07T02:00:00Z','Minute precision does not inherit current seconds');
$expect(local_datetime_to_utc("2030-05-07T09:00\0")===null,'Invalid datetime bytes rejected');
session_write_close();echo "PASS: $checks one-off checks\n";
