<?php

declare(strict_types=1);
if (PHP_SAPI !== 'cli') exit(1);
putenv('APP_ENV=local');
putenv('LUMS_DB_DSN=sqlite::memory:');
putenv('LUMS_SESSION_PATH=' . sys_get_temp_dir() . '/lums-planning-' . bin2hex(random_bytes(8)));
require dirname(__DIR__) . '/src/bootstrap.php';
initialize_database(db(), true);
start_lums_session();
$admin = (int)db()->query("SELECT id FROM users WHERE role='admin'")->fetchColumn();
$lecturer = (int)db()->query("SELECT id FROM users WHERE role='lecturer'")->fetchColumn();
$_SESSION['user_id'] = $admin;
$_SESSION['last_activity'] = time();
$checks = 0;
$expect = static function (bool $condition, string $message) use (&$checks): void {
    if (!$condition) throw new RuntimeException($message);
    $checks++;
};
$presets = nu_academic_presets();
$expect(count($presets[2568]['terms']) === 3, 'Verified year has exactly three terms.');
$expect(!isset($presets[2569]), 'Unverified years must not have guessed dates.');
$expect($presets[2568]['terms']['1'] === ['start'=>'2025-06-23', 'end'=>'2025-10-26'], 'First-semester dates match the NU source.');
$expect($presets[2568]['terms']['2'] === ['start'=>'2025-11-17', 'end'=>'2026-03-22'], 'Second semester crosses the Gregorian year.');
$expect($presets[2568]['terms']['summer'] === ['start'=>'2026-03-30', 'end'=>'2026-05-31'], 'Summer stays in academic year 2568.');
$expect(academic_term_code(2568, 'summer') === '2568/3', 'Summer displays as term 3.');
$expect(!valid_iso_date("2030-02-30") && !valid_iso_date("2030-01-01\0"), 'Impossible dates and null bytes are rejected.');
$expect(valid_iso_date('2028-02-29'), 'Leap day is valid.');
$input = ['academic_year'=>2573, 'semester'=>'1', 'term_starts_on'=>'2030-01-01', 'term_ends_on'=>'2030-01-31'];
$expect(!create_academic_term($input)['ok'], 'Manual dates require source confirmation.');
$term = create_academic_term($input+['dates_confirmed'=>'1']);
$expect($term['ok'], 'Confirmed manual year can be configured.');
$expect(get_academic_term($term['id'])['name'] === '2573/1', 'No free-text term name is required.');
$official = create_academic_term(['academic_year'=>2568, 'semester'=>'3', 'term_starts_on'=>'2026-03-30', 'term_ends_on'=>'2026-05-31']);
$expect($official['ok'] && get_academic_term($official['id'])['semester'] === 'summer', 'Official dates need no manual confirmation and 3 maps to summer.');
$rooms = list_rooms();
$room1 = $rooms[0]['id']; $room2 = $rooms[1]['id'];
$schedule = create_course_schedule(['term_id'=>$term['id'], 'room_id'=>$room1, 'lecturer_user_id'=>$admin, 'course_code'=>'TEST101', 'course_name'=>'ห้องทดลองข้อมูลสมมติ', 'day_of_week'=>1, 'starts_time'=>'08:30', 'ends_time'=>'10:30', 'active_from'=>'2030-01-01', 'active_until'=>'2030-01-31']);
$expect($schedule['ok'], 'Weekly fixture created.');
$created = create_session_from_schedule($schedule['id'], '2030-01-07');
$cancelled = create_session_from_schedule($schedule['id'], '2030-01-14');
$expect($created['ok'] && $cancelled['ok'], 'Linked class fixtures created.');
db()->prepare("UPDATE class_sessions SET room_id=?, status='closed' WHERE id=?")->execute([$room2, $created['id']]);
db()->prepare("UPDATE class_sessions SET status='cancelled' WHERE id=?")->execute([$cancelled['id']]);
$toUtc = static fn(string $local): string => (new DateTimeImmutable($local, new DateTimeZone('Asia/Bangkok')))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d\TH:i:s\Z');
$insert = db()->prepare("INSERT INTO class_sessions (room_id, lecturer_user_id, course_code, course_name, starts_at, ends_at, status, qr_token, created_at, updated_at) VALUES (?, ?, 'NIGHT', 'ทดสอบข้ามวัน', ?, ?, 'closed', ?, ?, ?)");
$insert->execute([$room1, $admin, $toUtc('2030-01-07 23:30'), $toUtc('2030-01-08 01:30'), bin2hex(random_bytes(16)), utc_now(), utc_now()]);
$nightId = (int)db()->lastInsertId();
$attendance = db()->prepare('INSERT INTO attendance_records (class_session_id, student_code, student_name, check_in_at, client_request_id, created_at) VALUES (?, ?, ?, ?, ?, ?)');
foreach ([$created['id'], $nightId] as $classId) foreach ([1,2] as $n) $attendance->execute([$classId, '9900000'.$n, 'ผู้ทดสอบสมมติ', utc_now(), bin2hex(random_bytes(10)), utc_now()]);
$events = room_usage_events('2030-01-01', '2030-01-31');
$expect(count($events) === 4, 'Four original Mondays become two plans, one class, and one standalone overnight class.');
$expect(count(array_filter($events, fn(array $e): bool => $e['schedule_id'] === $schedule['id'])) === 3, 'Linked class replaces its planned occurrence.');
$expect(room_usage_events('2030-01-14', '2030-01-14') === [], 'Cancelled occurrence must not reappear as a plan.');
$dayRoom1 = room_usage_events('2030-01-07', '2030-01-07', ['room_id'=>$room1]);
$expect(count($dayRoom1) === 1 && $dayRoom1[0]['class_id'] === $nightId, 'Moved class does not leave a ghost reservation in the original room.');
$dayRoom2 = room_usage_events('2030-01-07', '2030-01-07', ['room_id'=>$room2]);
$expect(count($dayRoom2) === 1 && $dayRoom2[0]['class_id'] === $created['id'], 'Moved class appears in the new room.');
$slices = room_usage_slices($events, '2030-01-01', '2030-01-31');
$nightSlices = array_values(array_filter($slices, fn(array $r): bool => $r['class_id'] === $nightId));
$expect(count($nightSlices) === 2, 'Overnight class appears on both dates.');
$expect(array_column($nightSlices, 'minutes') === [30.0, 90.0] || array_column($nightSlices, 'minutes') === [30,90], 'Overnight duration is split without loss.');
$expect(array_sum(array_column($nightSlices, 'counted_attendance')) === 2, 'Overnight attendance is not counted twice.');
$report = usage_report(planning_filters(['date_from'=>'2030-01-07', 'date_to'=>'2030-01-07', 'room_id'=>$room2, 'time_from'=>'09:00', 'time_to'=>'10:00'], true));
$expect($report['quantity'] === 1.0 || $report['quantity'] === 1, 'Hours are clipped to the requested clock-time interval.');
$expect($report['events'] === 1 && $report['attendees'] === 2, 'Report counts distinct classes and whole-class attendance.');
$periodReport = usage_report(planning_filters(['date_from'=>'2030-01-07', 'date_to'=>'2030-01-07', 'room_id'=>$room2, 'unit'=>'periods', 'period_minutes'=>50, 'group'=>'room'], true));
$expect(abs($periodReport['quantity']-2.4) < 0.0001, 'Equivalent periods are not rounded up.');
$expect(count($periodReport['groups']) === 1, 'Room grouping uses the same filtered rows.');
$table = usage_report_table($periodReport);
$expect($table['rows'][0][2] === '2.40' && $table['headers'][2] === 'คาบเทียบเท่า', 'Rendered/export table shares units and values.');
$expect(!array_key_exists('errors', usage_report_query($periodReport['filters'])), 'Export query excludes internal errors.');
foreach ([['date_from'=>'2030-02-30'], ['date_from'=>'2030-01-10','date_to'=>'2030-01-01'], ['date_from'=>'2030-01-01','date_to'=>'2031-01-02'], ['time_from'=>'12:00','time_to'=>'10:00'], ['room_id'=>999999]] as $bad) $expect(planning_filters($bad, true)['errors'] !== [], 'Invalid report filters rejected.');
$allReport = usage_report(planning_filters(['date_from'=>'2030-01-01','date_to'=>'2030-01-31','source'=>'all'], true));
$expect($allReport['events'] === 4 && $allReport['attendees'] === 4, 'All-source totals reconcile plans and classes without duplication.');
$searched = usage_report(planning_filters(['date_from'=>'2030-01-01','date_to'=>'2030-01-31','source'=>'all','q'=>'test101','sort'=>'desc'], true));
$expect($searched['events'] === 3, 'Search is case-insensitive without losing linked override reconciliation.');
$expect(usage_report_table($searched)['rows'][0][0] === '2030-01-28', 'Descending export and table ordering is deterministic.');
$_SESSION['user_id'] = $lecturer;
$expect(room_usage_events('2030-01-01','2030-01-31') === [], 'Lecturer calendar cannot expose another lecturer records.');
$expect(usage_report(planning_filters(['date_from'=>'2030-01-01','date_to'=>'2030-01-31','source'=>'all'], true))['events'] === 0, 'Reports retain lecturer scope.');
session_write_close();
echo "PASS: $checks planning and report checks\n";
