<?php
declare(strict_types=1);
if (PHP_SAPI!=='cli') exit(1);
putenv('APP_ENV=local');putenv('LUMS_DB_DSN=sqlite::memory:');putenv('LUMS_SESSION_PATH='.sys_get_temp_dir().'/lums-room-test-'.bin2hex(random_bytes(8)));
require dirname(__DIR__).'/src/bootstrap.php'; initialize_database(db(),true);start_lums_session();
$checks=0;$expect=static function(bool $ok,string $message) use (&$checks) {if(!$ok)throw new RuntimeException($message);$checks++;echo "PASS: $message\n";};
$admin=(int)db()->query("SELECT id FROM users WHERE role='admin'")->fetchColumn();$lecturer=(int)db()->query("SELECT id FROM users WHERE role='lecturer'")->fetchColumn();
$now=utc_now();$token=bin2hex(random_bytes(16));
db()->prepare("INSERT INTO rooms(code,name,building,floor,capacity,status,qr_token,created_at,updated_at) VALUES ('QR-TEST','ห้องทดสอบสมมติ','อาคารทดสอบ','1',2,'available',?,?,?)")->execute([$token,$now,$now]);$room=(int)db()->lastInsertId();
$token2=bin2hex(random_bytes(16));db()->prepare("INSERT INTO rooms(code,name,building,floor,capacity,status,qr_token,created_at,updated_at) VALUES ('QR-TEST2','ห้องสอง','อาคารทดสอบ','1',2,'available',?,?,?)")->execute([$token2,$now,$now]);$room2=(int)db()->lastInsertId();
$expect(public_room('bad')===null && public_room(str_repeat('f',32))===null,'Invalid and unknown room tokens reveal nothing');
$expect((int)public_room($token)['id']===$room,'Stable room token resolves room');
initialize_database(db(),false);$expect(public_room($token)!==null,'Additive initialization preserves printed room tokens');
$countClasses=(int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn();$countUsers=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();
$input=['person_code'=>'QR001','person_name'=>'ผู้ใช้สมมติ','person_role'=>'student','purpose'=>'ทำโครงงานสมมติ','client_request_id'=>bin2hex(random_bytes(16))];$receipt=bin2hex(random_bytes(32));
$first=record_room_visit($token,$input,$receipt);$expect($first['ok'],'Anonymous visit can start without a class');
$expect((int)db()->query('SELECT COUNT(*) FROM class_sessions')->fetchColumn()===$countClasses && (int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn()===$countUsers,'No fake class or user account is created');
$expect(record_room_visit($token,$input,$receipt)['duplicate'],'Retry of same request is idempotent');
$expect(!db()->inTransaction(),'Retry does not leave a transaction open');
$expect(!record_room_visit($token,$input,bin2hex(random_bytes(32)))['ok'],'Another receipt cannot replay request');
$expect(!record_room_visit($token2,array_replace($input,['client_request_id'=>bin2hex(random_bytes(16))]),bin2hex(random_bytes(32)))['ok'],'Same person cannot open another active visit in another room');
$expect(room_visit_receipt(bin2hex(random_bytes(32)))===null && !checkout_room_visit(bin2hex(random_bytes(32)))['ok'],'Unknown receipt cannot read or close a visit');
$expect(room_visit_receipt($receipt)['person_name']===$input['person_name'],'Own receipt resolves only own record');
$secondReceipt=bin2hex(random_bytes(32));$secondInput=array_replace($input,['person_code'=>'QR002','client_request_id'=>bin2hex(random_bytes(16))]);
$second=record_room_visit($token,$secondInput,$secondReceipt);$expect($second['ok'],'Multiple individual users may use an unscheduled room');
$thirdInput=array_replace($input,['person_code'=>'QR003','client_request_id'=>bin2hex(random_bytes(16))]);$thirdReceipt=bin2hex(random_bytes(32));
$expect(!record_room_visit($token,$thirdInput,$thirdReceipt)['ok'],'Capacity enforced for active visits');
$expect(record_room_visit($token,$input,$receipt)['ok'],'Own retry still succeeds when capacity full');
db()->prepare('UPDATE room_visits SET check_in_at=? WHERE id=?')->execute([gmdate('Y-m-d\TH:i:s\Z',time()-3600),$first['id']]);
$expect(checkout_room_visit($receipt)['ok'] && checkout_room_visit($receipt)['duplicate'],'Self checkout and retry are safe');
$expect(record_room_visit($token,$thirdInput,$thirdReceipt)['ok'],'Checkout frees one place');
$expect(!checkout_room_visit('',$second['id'],'ตรวจห้องแล้ว')['ok'],'Anonymous cannot force-close a record');
$_SESSION['user_id']=$lecturer;$_SESSION['last_activity']=time();$expect(!checkout_room_visit('',$second['id'],'ตรวจแล้ว')['ok'] && (bool)room_visit_report([])['errors'],'Lecturer cannot read or close unrelated public visits');
$_SESSION['user_id']=$admin;$expect(!checkout_room_visit('',$second['id'],'')['ok'],'Admin closure requires a reason');
$expect(checkout_room_visit('',$second['id'],'ตรวจห้องแล้ว ไม่มีผู้ใช้')['ok'],'Admin can close stale visit with reason');
$report=room_visit_report(['room_id'=>$room,'date_from'=>date('Y-m-d',time()-86400),'date_to'=>date('Y-m-d'),'unit'=>'periods','period_minutes'=>50]);
$expect(count($report['rows'])===3 && $report['active']===1,'Report includes all visit states in requested range');
$byId=array_column($report['rows'],null,'id');$expect(abs($byId[$first['id']]['minutes']-60)<0.1 && $byId[$second['id']]['minutes']===null,'Only self checkout has confirmed individual duration');
$table=room_visit_table($report);$expect($table['rows'][0][7]==='1.20' && $table['rows'][1][7]==='ไม่ทราบ','Period conversion differs from unknown admin-closed duration');
$expect(count(room_visit_report(['room_id'=>$room,'visit_status'=>'active'])['rows'])===1,'Active status filter');
$expect(count(room_visit_report(['room_id'=>$room,'q'=>'QR002'])['rows'])===1,'Search filter');
$expect((bool)room_visit_report(['date_from'=>'2026-02-30'])['errors'] && (bool)room_visit_report(['time_from'=>'14:00','time_to'=>'09:00'])['errors'],'Invalid date and time filters fail closed');
$expect(room_visit_report(['room_id'=>$room2])['rows']===[],'Room filter isolation');
$expect(!array_key_exists('receipt_hash',$report['rows'][0]),'Reports never contain receipt secrets');
unset($_SESSION['user_id']); checkout_room_visit($thirdReceipt);
db()->prepare("UPDATE rooms SET status='maintenance' WHERE id=?")->execute([$room]);
$expect(!record_room_visit($token,array_replace($thirdInput,['client_request_id'=>bin2hex(random_bytes(16))]),bin2hex(random_bytes(32)))['ok'],'Maintenance room blocks public entry');
db()->prepare("UPDATE rooms SET status='available' WHERE id=?")->execute([$room]);
$start=gmdate('Y-m-d\TH:i:s\Z',time()+600);$end=gmdate('Y-m-d\TH:i:s\Z',time()+4200);
db()->prepare("INSERT INTO class_sessions(room_id,lecturer_user_id,course_code,course_name,starts_at,ends_at,status,checkin_mode,admission_lead_minutes,qr_token,created_at,updated_at) VALUES (?,?,'QR-CLASS','คลาสทดสอบ',?,?,'open','scheduled',10,?,?,?)")->execute([$room,$lecturer,$start,$end,bin2hex(random_bytes(16)),$now,$now]);$class=(int)db()->lastInsertId();
$expect(count(room_current_classes($room,strtotime($start)-600))===1 && room_current_classes($room,strtotime($start)-601)===[],'Class route starts exactly ten minutes early');
$expect(room_current_classes($room,strtotime($end))===[],'Class route ends at lesson end');
$expect(!record_room_visit($token,array_replace($input,['client_request_id'=>bin2hex(random_bytes(16))]),bin2hex(random_bytes(32)))['ok'],'Stale no-class form cannot bypass newly created lesson');
foreach (['closed','draft'] as $status) {db()->prepare('UPDATE class_sessions SET status=? WHERE id=?')->execute([$status,$class]);$expect(count(room_current_classes($room))===1 && !record_room_visit($token,array_replace($input,['client_request_id'=>bin2hex(random_bytes(16))]),bin2hex(random_bytes(32)))['ok'],"$status class prevents no-class bypass");}
db()->prepare("UPDATE class_sessions SET status='cancelled' WHERE id=?")->execute([$class]);$expect(room_current_classes($room)===[],'Cancelled class does not reserve check-in routing');
$expect(!record_room_visit($token,array_replace($input,['person_role'=>'admin']),$receipt)['ok'],'Public form cannot invent an admin role');
$expect(!db()->inTransaction(),'All failure paths release transaction');
echo "Room visits: $checks checks passed\n";
