<?php
$rooms=list_rooms();
$activeVisits=db()->query('SELECT room_id,COUNT(*) AS total FROM room_visits WHERE check_out_at IS NULL GROUP BY room_id')->fetchAll(PDO::FETCH_KEY_PAIR);
$posterRoom=null;foreach ($rooms as $room) if ($room['id']===(int)($_GET['qr_room'] ?? 0)) $posterRoom=$room;
$roomTotal=count($rooms);$roomSearch=trim((string)($_GET['q'] ?? ''));
if ($roomSearch!=='') $rooms=array_filter($rooms,static fn($r)=>stripos($r['code'].' '.$r['name'].' '.$r['building'],$roomSearch)!==false);
?>
<header class="page-header"><div><h1>ห้องปฏิบัติการ</h1><p>QR เดียวติดหน้าห้อง ใช้ลงชื่อทั้งในคลาสและนอกคลาสได้ตลอด ไม่ต้องพิมพ์ใหม่ทุกครั้งที่มีคลาส</p></div></header>
<form method="get" class="filter-bar"><input type="hidden" name="page" value="rooms"><label class="field"><span>ค้นหาห้อง</span><input name="q" value="<?= e($roomSearch) ?>" placeholder="รหัสห้อง ชื่อห้อง หรืออาคาร" maxlength="100"></label><button class="button button--secondary" type="submit">ค้นหา</button><?php if ($roomSearch!==''): ?><a class="text-link" href="?page=rooms">ล้างคำค้น</a><?php endif; ?></form>
<div class="section-heading"><h2>รายการห้อง</h2><span class="result-count">พบ <?= count($rooms) ?> จาก <?= $roomTotal ?> ห้อง</span></div>
<?php if (!$rooms): ?><p class="inline-note" role="status">ไม่พบห้องที่ตรงกับคำค้น ลองค้นด้วยรหัสห้องหรืออาคาร</p><?php endif; ?>
<div class="table-wrap"><table class="data-table"><thead><tr><th>ห้องปฏิบัติการ</th><th>ตำแหน่ง</th><th>สถานะห้อง</th><th>นอกคลาสที่ยังไม่กดออก</th><th>การดำเนินการ</th></tr></thead><tbody>
<?php foreach ($rooms as $room): ?><tr><td><strong><?= e($room['code']) ?></strong><small><?= e($room['name']) ?></small></td><td><?= e($room['building'].' · ชั้น '.$room['floor']) ?></td><td><?= e($room['status']==='available'?($room['live_status']==='active'?'มีคลาสตามตาราง':'พร้อมรับการเข้าใช้'):status_label($room['status'])) ?></td><td><?= (int)($activeVisits[$room['id']] ?? 0) ?> คน<small>ความจุ <?= $room['capacity'] ?> คน</small></td><td><div class="button-group"><a class="button button--secondary" href="?page=rooms&amp;qr_room=<?= $room['id'] ?>" aria-haspopup="dialog">QR หน้าห้อง / พิมพ์</a><?php if ($room['status']==='available'): ?><a class="text-link" href="?page=classes&amp;room_id=<?= $room['id'] ?>&amp;new_once=1">สร้างคลาสเรียน</a><?php endif; ?></div></td></tr><?php endforeach; ?>
</tbody></table></div><p class="helper-text">จำนวนที่ยังไม่กดออกเป็นสถานะจากการลงชื่อ ไม่ใช่จำนวนคนที่ตรวจวัดในห้อง</p>
<?php if ($user['role']==='admin'): ?><p><a class="text-link" href="?page=reports&amp;tab=walkins&amp;visit_status=active">ตรวจรายการนอกคลาสที่ยังไม่กดออก</a></p><?php endif; ?>
<?php if ($posterRoom): ?>
<dialog class="term-dialog room-qr-dialog" id="room-qr-dialog" aria-labelledby="room-qr-title" open><header class="term-dialog__header"><div><h2 id="room-qr-title">QR ประจำห้อง <?= e($posterRoom['code']) ?></h2><p>พิมพ์ติดหน้าห้องได้ ใช้ลิงก์เดิมทุกคลาส</p></div><a href="?page=rooms" class="icon-button" data-close-room-qr aria-label="ปิด QR หน้าห้อง"><span data-icon="x"></span></a></header><div class="term-dialog__body">
<section class="room-qr-poster" data-room-poster><p>LUMS · ลงชื่อเข้าใช้ห้องปฏิบัติการ</p><h2><?= e($posterRoom['code']) ?></h2><h3><?= e($posterRoom['name']) ?></h3><div data-room-qr="<?= e(public_room_url($posterRoom['qr_code'])) ?>" role="img" aria-label="QR ประจำห้อง <?= e($posterRoom['code']) ?>"></div><p>สแกนก่อนเข้าใช้ · ตรวจชื่อห้อง · ลงชื่อของตนเอง</p><p>มีคลาส: เลือกลงชื่อเข้าเรียน<br>ไม่มีคลาส: ระบุวัตถุประสงค์ และกดออกเมื่อใช้เสร็จ</p></section>
<label class="field"><span>ลิงก์ประจำห้อง (ใช้แทนการสแกนได้)</span><input data-room-link value="<?= e(public_room_url($posterRoom['qr_code'])) ?>" readonly></label><p data-room-qr-feedback role="status"></p><div class="button-group"><button class="button button--secondary" data-copy-room-link type="button">คัดลอกลิงก์</button><a class="text-link" target="_blank" rel="noopener" href="<?= e(public_room_url($posterRoom['qr_code'])) ?>">เปิดหน้าลงชื่อ</a></div></div>
<footer class="term-dialog__actions"><button class="button button--secondary" data-download-room-qr type="button" disabled>ดาวน์โหลด QR (PNG)</button><button class="button button--primary" data-print-room-qr type="button" disabled>พิมพ์ป้าย / PDF</button></footer></dialog>
<?php endif; ?>
