<?php
$report=room_visit_report($_GET); $vf=$report['filters']; $table=room_visit_table($report);
$query=['page'=>'reports','tab'=>'walkins']+room_visit_report_query($vf);
$roomLabel='ทุกห้อง'; foreach (list_rooms() as $r) if ($r['id']===$vf['room_id']) $roomLabel=$r['code'];
$visitLabels=[''=>'ทุกสถานะ','active'=>'ยังไม่กดออก','self'=>'ผู้ใช้กดออกเอง','admin'=>'ผู้ดูแลปิดรายการ'];
$pages=max(1,(int)ceil(count($report['rows'])/50));$pageNo=min($pages,max(1,(int)($_GET['page_number'] ?? 1)));$printing=isset($_GET['print']);
$visible=$printing?$report['rows']:array_slice($report['rows'],($pageNo-1)*50,50,true);
?>
<section class="usage-report <?= $printing?'is-print-view':'' ?>">
<header class="page-header"><div><h1>รายงานการเข้าใช้นอกคลาส</h1><p>ข้อมูลจาก QR หน้าห้อง · แยกจากเวลาในตารางเรียน</p></div><?php if (!$report['errors']): ?><div class="schedule-header-actions"><a class="button button--secondary" target="_blank" rel="noopener" href="?<?= e(http_build_query($query+['print'=>1])) ?>">ฉบับพิมพ์ / PDF</a><a class="button button--primary" href="?<?= e(http_build_query(['download'=>'room-visits-csv']+room_visit_report_query($vf))) ?>">ส่งออก CSV</a></div><?php endif; ?></header>
<form method="get" class="report-filters" data-report-filters>
<input type="hidden" name="page" value="reports"><input type="hidden" name="tab" value="walkins">
<label class="field"><span>เข้าใช้ตั้งแต่วันที่</span><input type="date" name="date_from" value="<?= e($vf['date_from']) ?>" required></label>
<label class="field"><span>เข้าใช้ถึงวันที่</span><input type="date" name="date_to" value="<?= e($vf['date_to']) ?>" required></label>
<label class="field"><span>ห้องปฏิบัติการ</span><select name="room_id"><option value="0">ทุกห้อง</option><?php foreach (list_rooms() as $r): ?><option value="<?= $r['id'] ?>" <?= $r['id']===$vf['room_id']?'selected':'' ?>><?= e($r['code']) ?></option><?php endforeach; ?></select></label>
<label class="field"><span>สถานะการออก</span><select name="visit_status"><?php foreach ($visitLabels as $key=>$label): ?><option value="<?= $key ?>" <?= $key===$vf['visit_status']?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<details class="report-options" open><summary>เวลาเข้า คำค้น และหน่วยรายงาน</summary><div class="report-advanced-grid">
<label class="field"><span>เวลาเข้าตั้งแต่</span><input type="time" name="time_from" value="<?= e($vf['time_from']) ?>" required></label>
<label class="field"><span>เวลาเข้าก่อน</span><input name="time_to" value="<?= e($vf['time_to']) ?>" pattern="([01][0-9]|2[0-3]):[0-5][0-9]|24:00" required><small>24:00 = สิ้นวัน</small></label>
<label class="field"><span>ค้นหารหัส ชื่อ หรือวัตถุประสงค์</span><input name="q" value="<?= e($vf['q']) ?>" maxlength="100"></label>
<label class="field"><span>เรียงเวลาเข้า</span><select name="sort"><option value="asc" <?= $vf['sort']==='asc'?'selected':'' ?>>เก่าไปใหม่</option><option value="desc" <?= $vf['sort']==='desc'?'selected':'' ?>>ใหม่ไปเก่า</option></select></label>
<label class="field"><span>หน่วยเวลารายบุคคล</span><select name="unit"><option value="hours" <?= $vf['unit']==='hours'?'selected':'' ?>>ชั่วโมงรายบุคคล</option><option value="periods" <?= $vf['unit']==='periods'?'selected':'' ?>>คาบรายบุคคล</option></select></label>
<label class="field"><span>ความยาว 1 คาบ</span><select name="period_minutes" data-period-length><?php foreach ([50,60,90] as $n): ?><option value="<?= $n ?>" <?= $vf['period_minutes']===$n?'selected':'' ?>><?= $n ?> นาที</option><?php endforeach; ?></select></label>
</div></details><div class="report-filter-actions"><button class="button button--primary" type="submit">แสดงรายงาน</button><a class="button button--secondary" href="?page=reports&amp;tab=walkins">ล้างตัวกรอง</a></div></form>
<p class="inline-note" data-report-pending role="status" hidden>เปลี่ยนตัวกรองแล้ว กรุณากด “แสดงรายงาน” ก่อนส่งออก</p>
<?php if ($report['errors']): ?><p class="alert alert--error" role="alert"><?= e(implode(' ',$report['errors'])) ?></p><?php else: ?>
<div class="report-applied-filters"><h2><?= e(thai_date_label($vf['date_from']).' – '.thai_date_label($vf['date_to'])) ?></h2><p><?= e($roomLabel.' · '.$visitLabels[$vf['visit_status']].' · เวลาเข้า '.$vf['time_from'].'–'.$vf['time_to'].' น. (เวลาไทย)') ?></p><p><?= $vf['unit']==='periods'?'คาบรายบุคคล · 1 คาบ = '.e($vf['period_minutes']).' นาที':'ชั่วโมงรายบุคคล' ?> · <?= $vf['sort']==='desc'?'ใหม่ไปเก่า':'เก่าไปใหม่' ?><?= $vf['q']!==''?' · คำค้น: '.e($vf['q']):'' ?></p></div>
<p class="inline-note">ระยะเวลาคือเวลาเข้า–ออกทั้งรายการของแต่ละคนที่กดออกเอง ไม่ใช่ชั่วโมงการใช้ห้องรวม ตัวกรองเลือกตามเวลาเข้า หากยังไม่กดออกหรือผู้ดูแลปิดรายการ จะแสดงระยะเวลา “ไม่ทราบ” ไม่คำนวณเวลาแทนผู้ใช้</p>
<?php if ($printing): ?><div class="print-actions"><button class="button button--primary" type="button" data-print-report>พิมพ์ / บันทึกเป็น PDF</button></div><?php endif; ?>
<div class="section-heading"><h2>รายการเข้าใช้</h2><span class="result-count">พบ <?= count($report['rows']) ?> รายการ · ยังไม่กดออก <?= $report['active'] ?> รายการ · แสดง <?= count($visible) ?> รายการ<?= !$printing?' · หน้า '.$pageNo.'/'.$pages:'' ?></span></div>
<?php if (!$visible): ?><div class="empty-state"><strong>ไม่พบการเข้าใช้นอกคลาสตามตัวกรอง</strong><span>ลองขยายช่วงวันที่ หรือเลือกทุกห้อง การลงชื่อเข้าเรียนอยู่ในรายงานตารางและคลาสเรียน</span></div><?php else: ?>
<div class="table-wrap report-table-wrap"><table class="data-table report-data-table visit-report-table"><thead><tr><th>เวลาเข้า–ออก</th><th>ห้อง</th><th>ผู้เข้าใช้</th><th>วัตถุประสงค์</th><th>ระยะเวลาและสถานะ</th><?php if (!$printing): ?><th>จัดการรายการค้าง</th><?php endif; ?></tr></thead><tbody>
<?php foreach ($visible as $i=>$row): $cells=$table['rows'][$i]; ?><tr><td data-label="เวลาเข้า–ออก"><strong>เข้า <?= e($cells[0]) ?></strong><small><?= $row['checkout_method']==='admin'?'ปิดรายการ ':($row['check_out_at']?'ออก ':'') ?><?= e($cells[1]) ?></small></td><td data-label="ห้อง"><?= e($cells[2]) ?></td><td data-label="ผู้เข้าใช้"><strong><?= e($cells[4]) ?></strong><small><?= e($cells[3].' · '.$cells[5]) ?></small></td><td data-label="วัตถุประสงค์"><?= e($cells[6]) ?></td><td data-label="ระยะเวลาและสถานะ"><strong><?= e($cells[7]) ?><?= $row['minutes']!==null?($vf['unit']==='periods'?' คาบ':' ชั่วโมง'):'' ?></strong><small><?= e($cells[8]) ?></small><?php if ($cells[9]!==''): ?><small>เหตุผล: <?= e($cells[9]) ?></small><?php endif; ?></td><?php if (!$printing): ?><td><?php if (!$row['check_out_at']): ?><form method="post" action="?<?= e(http_build_query($query)) ?>" class="visit-row-action" data-confirm="ปิดรายการนี้โดยผู้ดูแล? ระบบจะบันทึกเวลาและเหตุผลที่ปิด แต่ไม่ถือเป็นเวลาออกที่ผู้ใช้ยืนยัน" data-confirm-title="ปิดรายการค้าง" data-confirm-label="ยืนยันปิดรายการ"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="room_visit_admin_end"><input type="hidden" name="visit_id" value="<?= $row['id'] ?>"><label class="field"><span>เหตุผลปิดรายการ <?= e($row['person_code']) ?></span><input name="checkout_note" minlength="2" maxlength="255" required></label><button class="button button--secondary" type="submit">ปิดรายการ</button></form><?php else: ?>—<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?>
</tbody></table></div>
<?php if (!$printing && $pages>1): ?><nav class="report-pagination" aria-label="หน้ารายงาน"><?php if ($pageNo>1): ?><a class="button button--secondary" href="?<?= e(http_build_query($query+['page_number'=>$pageNo-1])) ?>">หน้าก่อน</a><?php endif; ?><?php if ($pageNo<$pages): ?><a class="button button--secondary" href="?<?= e(http_build_query($query+['page_number'=>$pageNo+1])) ?>">หน้าถัดไป</a><?php endif; ?><small>CSV และฉบับพิมพ์รวมทุกหน้าที่ตรงตัวกรอง</small></nav><?php endif; ?>
<?php endif; endif; ?></section>
